### ISSUE TITLE
editor stylesheet

### ISSUE THREAD

**Issue by perruche** [studiometa/wordpress-project#26]
The added stylesheet from `TinyMCEManager.php`: `add_editor_style( get_template_directory_uri() . '/dist/css/admin/editor-style.css' );` does not work when using `npm run build`. 

The `withContentHash()` setting make the file name undetermined. 
This stylesheet cannot be inserted via `assets.yml` because it is injected inside the tinyMCE iframe. 

Is the hash readable to add it to the stylesheet uri ?

**Comment by titouanmathis** [comment]
This can be fixed by using the `AssetsManager` instance, I'll open a PR.
